Taq22100900058_lession12/Controllers/TaqHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Taq22100900058_lession11.Controllers
{
    public class TaqHomeController : Controller
    {
        public ActionResult TaqIndex()
        {
            return View();
        }

        public ActionResult TaqAbout()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult TaqContact()
        {
            ViewBag.msv = "2210900058";
            ViewBag.fullname = "truong anh quan ";

            return View();
        }
    }
}

Taq22100900058_lession12/Views/Shared/_Taq2201900058Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Taq2201900058 </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Truong Anh Quan", "TaqIndex", "TaqHome", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("TaqHome", "TaqIndex", "TaqHome", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("TaqAbout", "TaqAbout", "TaqHome", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("TaqContact", "TaqContact", "TaqHome", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("TaqCategory", "TaqContact", "TaqHome", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Taq2201900058</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>